[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.curl",
  "php83Extensions.mbstring",
  "php83Extensions.pdo_mysql",
  "php83Extensions.tokenizer",
  "php83Extensions.xml"
]

[phases.install]
cmds = [
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan cache:clear"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
