[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.curl",
  "php83Extensions.mbstring",
  "php83Extensions.pdo_mysql",
  "php83Extensions.tokenizer",
  "php83Extensions.xml",
  "nginx",
  "curl"
]

[phases.build]
cmds = [
  # install composer
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
  # buat symlink agar composer dikenal
  "ln -s /usr/local/bin/composer /bin/composer",
  # install dependency laravel
  "composer install --no-dev --optimize-autoloader",
  # generate app key
  "php artisan key:generate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
