[phases.setup]
nixPkgs = [
  "php83",
  "nginx",
  "php83Extensions.curl",
  "php83Extensions.mbstring",
  "php83Extensions.pdo_mysql",
  "php83Extensions.tokenizer",
  "php83Extensions.xml",
  "nodejs_20"
]

[phases.install]
cmds = [
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan cache:clear"
]

[start]
cmd = "vendor/bin/heroku-php-nginx public/"
