[phases.setup]
nixPkgs = [
  "php83",
  "nginx",
  "nodejs",
  "npm",
  "php83Extensions.curl",
  "php83Extensions.mbstring",
  "php83Extensions.pdo_mysql",
  "php83Extensions.tokenizer",
  "php83Extensions.xml"
]

[phases.install]
cmds = [
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "php artisan config:clear && php artisan cache:clear && php artisan route:clear && php artisan view:clear && php artisan migrate --force && vendor/bin/heroku-php-nginx public/"
